### ISSUE TITLE
How to bind cgcnn for matminer?

### ISSUE THREAD

**Issue by mm04926412** [txie-93/cgcnn#12]
Hello

I'm looking at the matminer documentation which asserts that it's cgcnn featurizer requires cgcnn with python bindings. How would I install cgcnn as a package rather than launch it from main.py?

**Comment by txie-93** [comment]
The easiest way would be to add the path to the repository to your PYTHONPATH. Or you can try to set up a pip install like in #4.

**Comment by txie-93** [comment]
Closing this. Feel free to reopen if you have more questions.

**Comment by craigerboi** [comment]
In my case, I updated the way the arguments are assigned in main.py to
`args, unknown = parser.parse_known_args()`
This way you don't necessarily need command-line arguments.
