### ISSUE TITLE
Issues about predication for example

### ISSUE THREAD

**Issue by yanweiqi123** [txie-93/cgcnn#13]
Hey，i have installed cgcnn and run **predict.py** successfully. 
As followed by readme, i tried "python predict.py pre-trained/formation-energy-per-atom.pth.tar data/sample-regression". However, the MAE predication was so huge, which indicates bad  accuracy of prediction. 
In my understanding，i can simply use pre-trained model to predict examples in /data to test cgcnn, but the results confused me. So am I doing something wrong at some step?

**Comment by txie-93** [comment]
No, you didn't do anything wrong. The `data/sample-regression` is a toy dataset with made-up numbers. The error should be high because the "true properties" are random numbers.

**Comment by yanweiqi123** [comment]
Oh, i see. So the second columns of id_prop.csv in sample-regression and sample-classification is made-up numbers, not the true properties of these materials. If i really want to use cgccn , i should write true properties in the second columns, such as band gap, formation energy, am i right? 
By the way, if the json is also made-up? If i should rewrite it for real application?

**Comment by txie-93** [comment]
Yes, you are right. You need to create your own dataset with true properties and structures. The json is not made-up. You can copy the json file to your own dataset.

**Comment by yanweiqi123** [comment]
OK, i see. Thank you!
