### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by shaziaj** [txie-93/cgcnn#14]
Hi, 
I was trying to create the env as per your README:
conda create -n cgcnn python=3.7 scikit-learn pytorch=1.0.0 torchvision pymatgen -c pytorch -c matsci

I got this following error, I am using Fedora30 and Anaconda is updated to the newest version.

LinkError: pre-link script failed for package matsci::pydispatcher-2.0.5-py_0
location of failed script: /home/shazia/anaconda3/pkgs/pydispatcher-2.0.5-py_0/bin/.pydispatcher-pre-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: + unset _mlshdbg
+ '[' 0 = 1 ']'
+ export MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH
+ MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH
+ unset _mlre _mlIFS
+ '[' -n x ']'
+ _mlIFS='
'
+ IFS=' '
+ for _mlv in ${MODULES_RUN_QUARANTINE:-}
+ '[' LD_LIBRARY_PATH = LD_LIBRARY_PATH -a LD_LIBRARY_PATH = LD_LIBRARY_PATH ']'
++ eval 'echo ${LD_LIBRARY_PATH+x}'
+++ echo x
+ '[' -n x ']'
++ eval 'echo ${LD_LIBRARY_PATH}'
+++ echo /usr/lib64/mpich/lib
+ _mlre='LD_LIBRARY_PATH_modquar='\''/usr/lib64/mpich/lib'\'' '
+ _mlrv=MODULES_RUNENV_LD_LIBRARY_PATH
++ eval 'echo ${MODULES_RUNENV_LD_LIBRARY_PATH:-}'
+++ echo
+ _mlre='LD_LIBRARY_PATH_modquar='\''/usr/lib64/mpich/lib'\'' LD_LIBRARY_PATH='\'''\'' '
+ '[' -n 'LD_LIBRARY_PATH_modquar='\''/usr/lib64/mpich/lib'\'' LD_LIBRARY_PATH='\'''\'' ' ']'
+ _mlre='eval LD_LIBRARY_PATH_modquar='\''/usr/lib64/mpich/lib'\'' LD_LIBRARY_PATH='\'''\'' '
++ eval 'LD_LIBRARY_PATH_modquar='\''/usr/lib64/mpich/lib'\''' 'LD_LIBRARY_PATH='\'''\''' /usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash autoinit
+++ LD_LIBRARY_PATH_modquar=/usr/lib64/mpich/lib
+++ LD_LIBRARY_PATH=
+++ /usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash autoinit
+ _mlcode='module() {
   unset _mlshdbg;
   if [ "${MODULES_SILENT_SHELL_DEBUG:-0}" = '\''1'\'' ]; then
      case "$-" in
         *v*x*) set +vx; _mlshdbg='\''vx'\'' ;;
         *v*) set +v; _mlshdbg='\''v'\'' ;;
         *x*) set +x; _mlshdbg='\''x'\'' ;;
         *) _mlshdbg='\'''\'' ;;
      esac;
   fi;
   unset _mlre _mlIFS;
   if [ -n "${IFS+x}" ]; then
      _mlIFS=$IFS;
   fi;
   IFS='\'' '\'';
   for _mlv in ${MODULES_RUN_QUARANTINE:-}; do
      if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" -a "${_mlv}" = "${_mlv#[0-9]}" ]; then
         if [ -n "`eval '\''echo ${'\''$_mlv'\''+x}'\''`" ]; then
            _mlre="${_mlre:-}${_mlv}_modquar='\''`eval '\''echo ${'\''$_mlv'\''}'\''`'\'' ";
         fi;
         _mlrv="MODULES_RUNENV_${_mlv}";
         _mlre="${_mlre:-}${_mlv}='\''`eval '\''echo ${'\''$_mlrv'\'':-}'\''`'\'' ";
      fi;
   done;
   if [ -n "${_mlre:-}" ]; then
      eval `eval ${_mlre}/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash '\''"$@"'\''`;
   else
      eval `/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash "$@"`;
   fi;
   _mlstatus=$?;
   if [ -n "${_mlIFS+x}" ]; then
      IFS=$_mlIFS;
   else
      unset IFS;
   fi;
   unset _mlre _mlv _mlrv _mlIFS;
   if [ -n "${_mlshdbg:-}" ]; then
      set -$_mlshdbg;
   fi;
   unset _mlshdbg;
   return $_mlstatus;
};
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl; export MODULES_CMD;
MODULESHOME=/usr/share/Modules; export MODULESHOME;
test 0;'
+ _mlret=0
+ '[' -n x ']'
+ IFS='
'
+ unset _mlIFS
+ unset _mlre _mlv _mlrv
+ '[' 0 -eq 0 ']'
+ eval 'module() {
   unset _mlshdbg;
   if [ "${MODULES_SILENT_SHELL_DEBUG:-0}" = '\''1'\'' ]; then
      case "$-" in
         *v*x*) set +vx; _mlshdbg='\''vx'\'' ;;
         *v*) set +v; _mlshdbg='\''v'\'' ;;
         *x*) set +x; _mlshdbg='\''x'\'' ;;
         *) _mlshdbg='\'''\'' ;;
      esac;
   fi;
   unset _mlre _mlIFS;
   if [ -n "${IFS+x}" ]; then
      _mlIFS=$IFS;
   fi;
   IFS='\'' '\'';
   for _mlv in ${MODULES_RUN_QUARANTINE:-}; do
      if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" -a "${_mlv}" = "${_mlv#[0-9]}" ]; then
         if [ -n "`eval '\''echo ${'\''$_mlv'\''+x}'\''`" ]; then
            _mlre="${_mlre:-}${_mlv}_modquar='\''`eval '\''echo ${'\''$_mlv'\''}'\''`'\'' ";
         fi;
         _mlrv="MODULES_RUNENV_${_mlv}";
         _mlre="${_mlre:-}${_mlv}='\''`eval '\''echo ${'\''$_mlrv'\'':-}'\''`'\'' ";
      fi;
   done;
   if [ -n "${_mlre:-}" ]; then
      eval `eval ${_mlre}/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash '\''"$@"'\''`;
   else
      eval `/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash "$@"`;
   fi;
   _mlstatus=$?;
   if [ -n "${_mlIFS+x}" ]; then
      IFS=$_mlIFS;
   else
      unset IFS;
   fi;
   unset _mlre _mlv _mlrv _mlIFS;
   if [ -n "${_mlshdbg:-}" ]; then
      set -$_mlshdbg;
   fi;
   unset _mlshdbg;
   return $_mlstatus;
};
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl; export MODULES_CMD;
MODULESHOME=/usr/share/Modules; export MODULESHOME;
test 0;'
++ MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
++ export MODULES_CMD
++ MODULESHOME=/usr/share/Modules
++ export MODULESHOME
++ test 0
+ '[' 0 = 1 ']'
+ '[' -t 2 ']'
+ export -f module
+ export -f switchml
+ ENV=/usr/share/Modules/init/profile.sh
+ export ENV
+ BASH_ENV=/usr/share/Modules/init/bash
+ export BASH_ENV
+ '[' 5 -ge 3 ']'
+ [[ hxB =~ i ]]
+ [[ ! :/home/shazia/anaconda3/pkgs/pydispatcher-2.0.5-py_0/bin:/home/shazia/anaconda3/bin:/home/shazia/anaconda3/bin:/home/shazia/anaconda3/condabin:/home/shazia/.local/bin:/home/shazia/bin:/usr/lib64/mpich/bin:/usr/share/Modules/bin:/usr/lib64ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin: =~ :/usr/share/Modules/bin: ]]
+ '[' '!' -n x ']'
++ manpath
+ [[ ! :/usr/share/man/mpich-x86_64::/home/shazia/anaconda3/man:/usr/local/share/man:/usr/share/man: =~ :/usr/share/man: ]]
+ unset _mlcode _mlret
+ '[' -n '' ']'
+ /home/shazia/anaconda3/envs/cgcnn/bin/python /home/shazia/anaconda3/pkgs/pydispatcher-2.0.5-py_0/link.py
/home/shazia/anaconda3/pkgs/pydispatcher-2.0.5-py_0/bin/.pydispatcher-pre-link.sh: line 2: /home/shazia/anaconda3/envs/cgcnn/bin/python: No such file or directory

return code: 127

**Comment by txie-93** [comment]
This looks like a problem of anaconda. May try to instal anaconda or ask in their forums?

**Comment by shaziaj** [comment]
Thank you!
