### ISSUE TITLE
Question: How to make dataset?

### ISSUE THREAD

**Issue by motonuko** [txie-93/cgcnn#15]
Hi

I have questions about datasets.

Materials Project database and API had changed a lot from when this repository started, and I can’t get the whole dataset written in the “cgcnn/data/material/mp-ids-○○.csv” file.

In CGCNN paper(https://arxiv.org/abs/1710.10324 ), it is written that

> After removing ill-converged crystals, the full database has 46744 materials covering 87 elements, ...

My questions are as follows.
- How to collect “mp-ids-27430", “mp-ids-46744”, “mp-ids-3402" like dataset?
-  What is the mean of _ill-converged crystal_ ?

Thanks,

**Comment by txie-93** [comment]
Hi, thanks for your question!

- Each line in `mp-ids-27430.csv` is a materials id in the Materials Project database. To get the data, one option is to write some code using the [pymatgen interface](https://pymatgen.org/pymatgen.ext.matproj.html) to download the structures and properties. An example code will be like:

```python
from pymatgen.ext.matproj import MPRester
  
with MPRester("API_KEY") as m:
    results = m.query(criteria={'material_id': 'mp-1234'},
                      properties=['formation_energy_per_atom', 'structure'])
    formation_energy = results['formation_energy_per_atom']
    structure = results['structure']
```
You can get the `"API_KEY"` by registering an account at their website.

- We removed all crystals with a warning label in their calculations. And we only included crystals with fully-computed band structures for the band gap predictions. This may not be the best way to define *ill-converged crystal*. Our thought at the time was to only include the highest quality data.

Hope that is helpful!

**Comment by motonuko** [comment]
Thanks for your explanation!  It is vary helpful for me. 

I found a change in materials project ([https://discuss.matsci.org/t/change-in-materials-project-ids/1268](https://discuss.matsci.org/t/change-in-materials-project-ids/1268) ), and some 'materials_id' has changed to 'task_id'. Taking this change into account, I got similar datasets. 

Thanks,
