### ISSUE TITLE
Description of crys_fea in model.py

### ISSUE THREAD

**Issue by sgbaird** [txie-93/cgcnn#23]
Hi,

What is `crys_fea`? I can't seem to find a description of it in the comments of model.py. Based on your suggestion in #21, it seems like this is the intermediate layer we're interested in. I assume it's the crystal feature vector. If that's the case, any help on what that actually means? Is there a place in the CGCNN paper that I should refer to?

Thank you,

Sterling

@mliu7051

**Comment by txie-93** [comment]
`crys_fea` is the feature vector you get after pooling -- `v_c` in Eq. 2.
