### ISSUE TITLE
What does 'target' means in id_prop.csv??

### ISSUE THREAD

**Issue by Amadeus-System** [txie-93/cgcnn#24]
Hi. I`m currently researching about your cgcnn paper and implementation of it.
I have reviewed your entire cgcnn code and now i`m trying to run my own custom code with custom dataset.
But I don't understand meaning of 'target' in data/sample-regression/id_prop.csv. 
Ten target values(1.0, 2.0, ... 10.0) are attached to each material-id(unique crystal number). what is it exactly? 
I hope your explanation.

Thank you!

**Comment by txie-93** [comment]
"target" is the property you want to predict. `data/sample-regression/id_prop.csv` is a toy dataset. I made up those numbers. In a real dataset, the column will include the property you hope to predict.

**Comment by Amadeus-System** [comment]
Oh! I got it.
I have implemented my own custom code!
Thank you.
