### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by ardunn** [txie-93/cgcnn#3]
Are there any plans to make CGCNN compatible with Pytorch 0.4+ (or even v1.0+)?

I ask because it seems like on some linux distributions (e.g. computing clusters) the required version is not available:

```bash
ardunn@n0001:~$ pip install torch==0.3.1
Collecting torch==0.3.1
  Could not find a version that satisfies the requirement torch== (from versions: 0.1.2, 0.1.2.post1, 0.4.1, 0.4.1.post2, 1.0.0)
No matching distribution found for torch==0.3.1
```

Whereas on other versions (e.g., Mac), the version is available.

**Comment by txie-93** [comment]
Sorry for the late response. We will support PyTorch v1.0+ soon. #7
