### ISSUE TITLE
Issue with path assertion for root_dir

### ISSUE THREAD

**Issue by daybl** [txie-93/cgcnn#6]
Hi! 
I've been trying to get this running but it does not seem to be able to find my root_dir. i've just been trying to have it run a regression and using this line exactly:

(cgcnn) blake@blake-desktop:~/cgcnn$ python main.py --disable-cuda --train-size 250 -- val-size 25 --test-size 20 root_dir
Traceback (most recent call last):
  File "main.py", line 488, in <module>
    main()
  File "main.py", line 85, in main
    dataset = CIFData(*args.data_options)
  File "/home/blake/cgcnn/cgcnn/data.py", line 288, in __init__
    assert os.path.exists(root_dir), 'root_dir does not exist!'
AssertionError: root_dir does not exist!
I've tried having the the root_dir directory in the cgcnn folder and outside of it in my home directory but both have resulted in the same error. If it matters or helps, I'm running Ubuntu 18.10 cosmic cuttlefish.

**Comment by txie-93** [comment]
`root_dir` is a directory where you store your dataset. For example, `data/sample-regression/` is an example dataset directory. You can check out our README for more details.
